name: .NET Core MVC w Azure SQL in docker for contosobikes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  AZURE_WEBAPP_NAME: contosobikessql

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.1.20452.10
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
#    - name: Docker Build and Push
#      run: |
#        docker build . -t gregroe/contosobikes:1.0.0
#    - name: Docker login 
#      env:
#        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
#        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
#      run: |
#         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
#    - name: Docker push
#      run: |
#        docker push gregroe/contosobikes:1.0.0

    - uses: azure/docker-login@v1
      with:
       login-server: consotobikes.azurecr.io
       username: ${{ secrets.ACR_USERNAME }}
       password: ${{ secrets.ACR_PASSWORD }}

    - run: |
       docker build . -t contosobikes.azurecr.io/contosobikes:${{ github.sha }}
       docker push contosobikes.azurecr.io/contosobikes:${{ github.sha }}









        
    
